apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quarkus-jpa-mysql-native
spec:
  template:
    spec:
      containers:
        - image: ivanfranchin/quarkus-jpa-mysql-native:1.0.0
          env:
            - name: MYSQL_HOST
              value: my-mysql
            - name: QUARKUS_PROFILE
              value: database-generation-update,native
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
