apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: springboot-consumer-api-native
spec:
  template:
    spec:
      containers:
        - image: ivanfranchin/springboot-consumer-api-native:1.0.0
          env:
            - name: KAFKA_HOST
              value: my-cluster-kafka-bootstrap.kafka
            - name: KAFKA_PORT
              value: "9092"
            - name: SPRING_PROFILES_ACTIVE
              value: native
---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: consumer-news
spec:
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topics:
    - springboot.news.native.json
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: springboot-consumer-api-native
