apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: springboot-kafka-producer-native
spec:
  template:
    spec:
      containers:
        - image: ivanfranchin/springboot-kafka-producer-native:latest
          env:
            - name: KAFKA_HOST
              value: my-cluster-kafka-bootstrap.kafka
            - name: KAFKA_PORT
              value: "9092"
            - name: SPRING_PROFILES_ACTIVE
              value: native
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false